### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by msfjarvis** [RiteshSaxena/Reloaded_tomato#2]
Please test your shit locally before pushing it to github, or don't pick anything from my kernel at all. Force pushing twice an hour is ridiculous

**Comment by h2o64** [comment]
Oops, wrong repo I think https://github.com/halogenOS/android_device_yu_jalebi/commits/XOS-7.1 ^^

**Comment by msfjarvis** [comment]
@h2o64 you mean this https://github.com/yu-community-os/android_vendor_volte/commits/cyos-7.1

**Comment by h2o64** [comment]
Hell no ! I'm only talking about your quality content man xD

**Comment by msfjarvis** [comment]
Much appreciated :smile:

**Comment by h2o64** [comment]
It was highly ironic ..

**Comment by DroidThug** [comment]
Everyone gets it

**Comment by msfjarvis** [comment]
@DroidThug he clearly doesn't
